test(markdownfmt): Don't shell out to 'diff'
Instead of shelling out to diff to determine if two files are equal,
use [go-cmp].
This is the recommended approach per [Go Test Comments].

[go-cmp]: https://pkg.go.dev/github.com/google/go-cmp/cmp
[Go Test Comments]: https://github.com/golang/go/wiki/TestComments#equality-comparison-and-diffs

Sample output after deleting a line from example1.output.md.

```
--- FAIL: TestDifferent (0.00s)
    --- FAIL: TestDifferent/testfiles/example1.input.md (0.00s)
        markdownfmt_test.go:117: Difference in testfiles/example1.input.md of 11 lines:
              (
                """
                ... // 13 identical lines
              
                ```go
            +   f, err := os.Open(something)
                if err != nil {
                        // handle..
                ... // 27 identical lines
                """
              )
```